Repository Tunnelsats/tunnelsats, pull requests merged in 2022-11, with the labels that each got.

#66 Added more VPN providers
  FAQ.md
Labels: enhancement

#73 raspiblitz-killswitch-bugfix
  scripts/setupv2.sh
Labels: bug

#72 Minor changes to FAQ.md
  FAQ.md
Labels: documentation
