Repository Tunnelsats/tunnelsats, pull requests merged in 2022-10, with the labels that each got.

#55 bugfix: nftables rule
  scripts/setupv2.sh
Labels: bug

#56 fix: umbrel stop/start cmds, final message
  scripts/setupv2.sh
Labels: bug

#57 guide: cln instructions per setup
  README.md
Labels: documentation

#59 check for plausible tunnelsatsv2 file
  scripts/setupv2.sh
Labels: enhancement
