Repository Tunnelsats/tunnelsats, pull requests merged in 2022-09, with the labels that each got.

#23 Update setupv2.sh
  scripts/setupv2.sh
Labels: enhancement

#25 Update setupv2.sh
  scripts/setupv2.sh
Labels: enhancement

#33 Hotfix: getWireguardConfig, TS logo
  README.md
  frontend/server/server.js
Labels: bug

#34 Hotfix: getWireguardConfig, TS logo
  README.md
  frontend/server/server.js
Labels: bug

#45 Reconfigure VPN handling
  frontend/client/src/App.js
  frontend/server/server.js
Labels: update

#35 compatibility check script
  scripts/check.sh
Labels: enhancement

#47 a whole lot of updates
  README.md
  frontend/client/package.json
  frontend/client/src/App.js
  frontend/client/src/components/HeaderInfo.js
  frontend/client/src/components/WorldMap.js
  frontend/client/src/components/WorldMapRenew.js
  frontend/server/server.js
  scripts/check.sh
Labels: update
